<div class="jumbotron">
    <h1>Welcome to <span class="text-primary">Uranium</span></h1>
    <p>Tweets your Github activity.</p>
    <p><a class="btn btn-primary btn-lg" href="https://github.com/srayner/uranium" target="_blank">Fork Uranium on Github &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-6">
        <h2>Github Settings</h1>
        <p>Configure the settings for your Github account.</p>
        <button class="btn btn-primary">Github Settings</button>
    </div>

    <div class="col-md-6">
        <h2>Twitter Settings</h1>
        <p>Configure the settings for your Twitter account.</p>
        <button class="btn btn-primary">Twitter Settings</button>
    </div>


</div>
